MacOS!

diff --git a/Jake/tests/Makefile b/Jake/tests/Makefile
--- a/Jake/tests/Makefile
+++ b/Jake/tests/Makefile
@@ -1,6 +1,6 @@
-# Jake 1.0.7 - A Servant for Lilly     (compiled on: Apr 29 2019 at: 10:44:49)
+# Jake 1.0.7 - A Servant for Lilly     (compiled on: Apr 29 2019 at: 11:16:45)
 
-TEXFILE      := UBdata.tex
+TEXFILE      := test.tex
 BASENAME     := $(basename $(TEXFILE))
 PDFFILE      := $(addsuffix .pdf,$(basename $(TEXFILE)))
 LATEXARGS    := -shell-escape -enable-write18 -interaction=batchmode
@@ -17,7 +17,7 @@ N            := 42                            ## Anzahl
 _C           := ,                             ## No Joke xD
 
 ## Makefile/General settings
-_LILLYARGS   :=  \\providecommand{\\LILLYxDOCUMENTNAME{$(TEXFILE)}}\\providecommand{\\LILLYxOUTPUTDIR{$(OUTPUTDIR)}} $(DEBUG) \\providecommand{\\LILLYxPATH}{${INPUTDIR}}\\providecommand{\\lillyPathLayout}{\\LILLYxgetDOCPATH/}\\providecommand{\\LILLYxEXTERNALIZE}{FALSE}
+_LILLYARGS   :=  \\providecommand{\\LILLYxDOCUMENTNAME{$(TEXFILE)}}\\providecommand{\\LILLYxOUTPUTDIR{$(OUTPUTDIR)}} $(DEBUG) \\providecommand{\\LILLYxPATH}{${INPUTDIR}}\\providecommand{\\lillyPathLayout}{\\LILLYxgetDOCPATH/P/}\\providecommand{\\LILLYxEXTERNALIZE}{FALSE}
 
 JOBCOUNT     := 2                             ## should: <= cpu/thread count!
 
@@ -27,11 +27,15 @@ void = true
 
 LILLYxCompile = \
     echo "Lilly PRE-Hook[hello-world] evaluiert zu: $(shell echo Hello World)" && \
+    echo "Lilly PRE-Hook[testhook] evaluiert zu: $(shell (touch testfile) >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  ["Ist gut gelaufen"] ||  echo  [failure])" && \
     mkdir -p "$(OUTPUTDIR)" && \
     touch $(OUTPUTDIR)LILLY_COMPILE.log && echo LILLY_LOGFILE stamp: $(shell date +'%d.%m.%Y %H:%M:%S') > $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 &&\
     (for bm in $(BOXMODES); do \
+    echo "Lilly IN0-Hook[in0-hook] evaluiert zu: $(shell (echo "Hallo Welt - will it break?") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [""] ||  echo  [failure])" && \
        pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
+    echo "Lilly IN1-Hook[in1-hook] evaluiert zu: $(shell (echo "Hallo Welt") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [success] ||  echo  ["It's dead"])" && \
        pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
+    echo "Lilly IN2-Hook[in2-hook] evaluiert zu: $(shell (echo "Hallo Welt 2") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [success] ||  echo  ["It's dead"])" && \
        pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
        echo "\033[38;2;102;250;0mGenerierierung von "${1}$${bm}-${2}" ($${bm}) abgeschlossen\033[m"; done &&\
     echo "Lilly POST-Hook[hello-world-out] evaluiert zu: $(shell echo Hello World - I am out)" && \
@@ -41,16 +45,20 @@ LILLYxClean = echo "\033[38;2;255;191;0m> Lösche temporäre Dateien...[m" && \
      for fd in $(CLEANTARGETS); do rm -f $(OUTPUTDIR)*.$$fd; done
 
 
-uebungsblatt: $(INPUTDIR)$(TEXFILE)
-	@echo "\033[38;2;255;191;0mGeneriere COMPLETE-Übungsblatt-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
-	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)COMPLETE-,$(PDFFILE),\\providecommand\\LILLYxMODE{default}\\providecommand\\LILLYxMODExEXTRA{TRUE},"\\documentclass[Typ=Uebungsblatt${_C}Vorlesung=${VORLESUNG}${_C}n=${N}${_C}Semester=${SEMESTER}]{Lilly}\\begin{document}\\input{$(INPUTDIR)$(TEXFILE)}\\end{document}")
+default: $(INPUTDIR)$(TEXFILE)
+	@echo "\033[38;2;255;191;0mGeneriere Standart-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
+	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX),$(PDFFILE),\\providecommand\\LILLYxMODE{default}\\providecommand\\LILLYxMODExEXTRA{FALSE},"\\input{$(INPUTDIR)$(TEXFILE)}")
+
+print: $(INPUTDIR)$(TEXFILE)
+	@echo "\033[38;2;255;191;0mGeneriere Druck-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
+	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)PRINT-,$(PDFFILE),\\providecommand\\LILLYxMODE{print}\\providecommand\\LILLYxMODExEXTRA{FALSE},"\\input{$(INPUTDIR)$(TEXFILE)}")
 
 
 all: $(INPUTDIR)$(TEXFILE)
-	@$(MAKE) -s --no-print-directory uebungsblatt  CLEANTARGET=void -j ${JOBCOUNT} --output-sync=line
+	@$(MAKE) -s --no-print-directory default print  CLEANTARGET=void -j ${JOBCOUNT} --output-sync=line
 	@$(MAKE) -s --no-print-directory clean
 
 clean:
 	@$(call LILLYxClean)
 
-.PHONY: uebungsblatt all clean
+.PHONY: default print all clean
