:EagleoutIce for Lilly ============================================================================================
Jake trifft Captain Hook & Einige Änderungen

JAKE:

    * Der GeneratorParser unterstützt nun mehrere durch ':' getrennte Pfade - das ist cool

    * Der REGEX-Ausdruck für GeParD wurde freier und auch einfacher gestaltet

    * !!!!! buildrule-path heißt nun gepardrule-path!!!!!

    + Jake beginnt nun, neben 'dump' ein grunlegendes Debug-System zu integrieren um die
      Fehlersuche zu erleichtern.

    + GeParD unterstützt und forciert nun verpflichtende Argumente

    + Es gibt nun (verbesserte) PRE- und POST-Hooks (ALL und IN sind TODO)

    + Hinzufügen der (lightweight-Variante der) Debug-Bibliothek aus dem EAGLE-Framework (Juchey :D)

    + Endlich gibt es nun die Einstellung: 'lilly-show-boxname' um Boxnamen auszublenden wenn man nur einen
      Boxtyp kompiliert :D

    ! FIX: GePard Boxmode Beispiele

LILLY:

    ! FIX \LILLY@Semster to \LILLY@Semester typo

    ! PROBLEM: \ifx\\LILLYxBOXxLemmaxBox wird nicht richtig aufgelöst im Modecontroller

    + PDP hat nun ein ordentliches Profilbild (mit Random-Color on Compile Bonus)

    + Es gibt nun die neue Farbe Butter - Weil ichs ie mag
      Ebenfalls gibt es noch Leaf und MudWhite aus den gleichen gründen

    + Es gibt nun `\Hcolor` und `\HBcolor` um generelle Highlighting Farben für Lilly zu
      standartisieren.

    * Edited DarkMidnightBlue für bessere Lesbarkeit

    * Es wurden einige Korrekturen an den Daten für die Vorlesungen vorgenommen.

    * Der Style bash wurde angepasst um Druckerfreundlich zu sein.

    * Es gibt nun eine auf der Sprache C++ aufbauende neue Sprache Cpp für lstlistings

    - Das Print-Profil liefert nun keine Farben mehr, dies war ohnehin überflüssig

============================================================================================
:

diff --git a/Lilly/Jake/tests/Makefile b/Lilly/Jake/tests/Makefile
--- a/Lilly/Jake/tests/Makefile
+++ b/Lilly/Jake/tests/Makefile
@@ -1,4 +1,4 @@
-# Jake 1.0.7 - A Servant for Lilly     (compiled on: Apr 23 2019 at: 11:48:10)
+# Jake 1.0.7 - A Servant for Lilly     (compiled on: Apr 25 2019 at: 00:05:10)
 
 TEXFILE      := test.tex
 BASENAME     := $(basename $(TEXFILE))
@@ -26,13 +26,16 @@ void = true
 
 
 LILLYxCompile = \
+    echo Lilly Pre-Hook[hello-world] evaluiert zu: $(shell echo Hello World) && \
+    echo Lilly Pre-Hook[testhook] evaluiert zu: $(shell touch testfile && echo  ["Ist gut gelaufen"] ||  echo  [failure]) && \
     mkdir -p "$(OUTPUTDIR)" && \
     touch $(OUTPUTDIR)LILLY_COMPILE.log && echo LILLY_LOGFILE stamp: $(shell date +'%d.%m.%Y %H:%M:%S') > $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 &&\
     (for bm in $(BOXMODES); do \
-       pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
-       pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
-       pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
-       echo "\033[38;2;102;250;0mGenerierierung von "${1}$${bm}-${2}" ($${bm}) abgeschlossen\033[m"; done &&\
+       pdflatex -jobname $(basename ${1}${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
+       pdflatex -jobname $(basename ${1}${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
+       pdflatex -jobname $(basename ${1}${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
+       echo "\033[38;2;102;250;0mGenerierierung von "${1}${2}" ($${bm}) abgeschlossen\033[m"; done &&\
+    echo Lilly Post-Hook[hello-world-out] evaluiert zu: $(shell echo Hello World - I am out) && \
     $(call $(CLEANTARGET)) ) || (echo "\033[31m! Das Kompilieren mit LILLY ist fehlgeschlagen. Fehler finden sich in der entsprechendne Logdatei\033[m"; exit 1;)
 
 LILLYxClean = echo "\033[38;2;255;191;0m> Lösche temporäre Dateien...[m" && \
@@ -41,18 +44,30 @@ LILLYxClean = echo "\033[38;2;255;191;0m> Lösche temporäre Dateien...[m" && \
 
 default: $(INPUTDIR)$(TEXFILE)
 	@echo "\033[38;2;255;191;0mGeneriere Standart-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
-	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX),$(PDFFILE),\\providecommand\\LILLYxMODE{default}\\providecommand\\LILLYxMODExEXTRA{FALSE},"\\input{$(INPUTDIR)$(TEXFILE)}")
+	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)MY-DEFAULT-,$(PDFFILE),\\providecommand\\LILLYxMODE{default}\\providecommand\\LILLYxMODExEXTRA{FALSE},"\\input{$(INPUTDIR)$(TEXFILE)}")
+
+c_default: $(INPUTDIR)$(TEXFILE)
+	@echo "\033[38;2;255;191;0mGeneriere COMPLETE-Standart-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
+	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)COMPLETE-MY-DEFAULT-,$(PDFFILE),\\providecommand\\LILLYxMODE{default}\\providecommand\\LILLYxMODExEXTRA{TRUE},"\\input{$(INPUTDIR)$(TEXFILE)}")
 
 print: $(INPUTDIR)$(TEXFILE)
 	@echo "\033[38;2;255;191;0mGeneriere Druck-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
-	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)PRINT-,$(PDFFILE),\\providecommand\\LILLYxMODE{print}\\providecommand\\LILLYxMODExEXTRA{FALSE},"\\input{$(INPUTDIR)$(TEXFILE)}")
+	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)MY-PRINT-,$(PDFFILE),\\providecommand\\LILLYxMODE{print}\\providecommand\\LILLYxMODExEXTRA{FALSE},"\\input{$(INPUTDIR)$(TEXFILE)}")
+
+c_print: $(INPUTDIR)$(TEXFILE)
+	@echo "\033[38;2;255;191;0mGeneriere COMPLETE-Druck-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
+	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)COMPLETE-MY-PRINT-,$(PDFFILE),\\providecommand\\LILLYxMODE{print}\\providecommand\\LILLYxMODExEXTRA{TRUE},"\\input{$(INPUTDIR)$(TEXFILE)}")
+
+Waffel: $(INPUTDIR)$(TEXFILE)
+	@echo "\033[38;2;255;191;0mGeneriere DEMO-WAFFEL-Version($(BOXMODES)) der Latex-Datei: "$(TEXFILE)"...\033[m"
+	@$(call LILLYxCompile,$(OUTPUTDIR)$(NAMEPREFIX)waffel-,$(PDFFILE),\\providecommand\\LILLYxMODE{default}\\providecommand\\LILLYxMODExEXTRA{FALSE},"\\input{$(INPUTDIR)$(TEXFILE)}")
 
 
 all: $(INPUTDIR)$(TEXFILE)
-	@$(MAKE) -s --no-print-directory default print  CLEANTARGET=void -j ${JOBCOUNT} --output-sync=line
+	@$(MAKE) -s --no-print-directory default c_default print c_print Waffel c_Waffel  CLEANTARGET=void -j ${JOBCOUNT} --output-sync=line
 	@$(MAKE) -s --no-print-directory clean
 
 clean:
 	@$(call LILLYxClean)
 
-.PHONY: default print all clean
+.PHONY: default c_default print c_print Waffel c_Waffel all clean
