Jetzt auch ohne Befehle
============================================================================================
:EagleoutIce for Lilly
============================================================================================

JAKE:

    * Jake installation für MikTeX wurde angepasst

    * Die neue REGEX-Expression für die Configurator wurde angepasst

    * Default Name-Maps wurde entsprechend angepasst

LILLY:

    + Durch das definieren von '\LILLYxCMD' vor dem einbinden von Lilly
      können nun Shellbefehle die direkt von LILLY ausgeführt werden verhindert werden.
      Die option 'external' steht allerdings nach wie vor zu verfügung und kann diese
      nach wie vor einsetzen.

    * Exemplarische Universe-Übersetzungspaket hinzugefügt

    * Pfad für Tikz-Dateien angepasst TODO anpassen doku

ALLGEMEIN:

    + Es wurde ein Wiki-Template eingeführt
      (https://github.com/EagleoutIce/LILLY/wiki/conf-Einstellungen)

============================================================================================
:

diff --git a/Jake/tests/map_tests/Makefile b/Jake/tests/map_tests/Makefile
--- a/Jake/tests/map_tests/Makefile
+++ b/Jake/tests/map_tests/Makefile
@@ -1,4 +1,4 @@
-# Jake 1.0.8 - An intelligent Servant for Lilly     (compiled on: May  5 2019 at: 18:12:59)
+# Jake 1.0.8 - An intelligent Servant for Lilly     (compiled on: May  7 2019 at: 00:00:01)
 
 TEXFILE      := Mitschrieb-GDBS.tex
 BASENAME     := $(basename $(TEXFILE))
@@ -10,7 +10,8 @@ INPUTDIR     := $(shell echo ./| sed 's:/*$$::')/
 BOXMODES     := DEFAULT#                      ## Seperator: ' '
 CLEANTARGET  := LILLYxClean
 CLEANTARGETS := log aux out ind bbl blg lof lot toc idx acn acr alg glg glo gls fls fdb_latexmk auxlock SATZE ZSM UB TOP listing upa ilg TOPIC DEFS
-AUTHOR       := Florian der Echte von Sieben
+SIGNATURECOL := Leaf
+AUTHOR       := Florian Sihler
 AUTHORMAIL   := florian.sihler@web.de
 NAMEPREFIX   := #                             ## Immer
 SEMESTER     := 2#                            ## Übungsblatt
@@ -19,7 +20,7 @@ N            := 42#                           ## Anzahl
 _C           := ,                             ## No Joke xD
 
 ## Makefile/General settings
-_LILLYARGS   :=  \\providecommand{\\LILLYxDOCUMENTNAME{$(TEXFILE)}}\\providecommand{\\LILLYxOUTPUTDIR{$(OUTPUTDIR)}} $(DEBUG) \\providecommand{\\LILLYxPATH}{${INPUTDIR}}\\providecommand{\\AUTHOR}{${AUTHOR}}\\providecommand{\\AUTHORMAIL}{${AUTHORMAIL}}\\providecommand{\\LILLYxSemester}{${SEMESTER}}\\providecommand{\\LILLYxVorlesung}{${VORLESUNG}}\\providecommand{\\lillyPathLayout}{\\LILLYxgetDOCPATH/}\\providecommand{\\LILLYxEXTERNALIZE}{FALSE}
+_LILLYARGS   :=  \\providecommand{\\LILLYxDOCUMENTNAME{$(TEXFILE)}}\\providecommand{\\LILLYxOUTPUTDIR{$(OUTPUTDIR)}} $(DEBUG) \\providecommand{\\LILLYxPATH}{${INPUTDIR}}\\providecommand{\\AUTHOR}{${AUTHOR}}\\providecommand{\\AUTHORMAIL}{${AUTHORMAIL}}\\providecommand{\\LILLYxSemester}{${SEMESTER}}\\providecommand{\\LILLYxVorlesung}{${VORLESUNG}}\\providecommand{\\Hcolor}{${SIGNATURECOL}}\\providecommand{\\lillyPathLayout}{\\LILLYxgetDOCPATH/}\\providecommand{\\LILLYxEXTERNALIZE}{FALSE}
 
 JOBCOUNT     := 2#                            ## should: <= cpu/thread count!
 
@@ -33,11 +34,11 @@ LILLYxCompile = \
     mkdir -p "$(OUTPUTDIR)" && \
     touch $(OUTPUTDIR)LILLY_COMPILE.log && echo LILLY_LOGFILE stamp: $(shell date +'%d.%m.%Y %H:%M:%S') > $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 &&\
     (for bm in $(BOXMODES); do \
-    echo "Lilly IN0-Hook[in0-hook] evaluiert zu: $(shell (echo "Hallo Welt - will it break) >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [""] ||  echo  [failure])" && \
+    echo "Lilly IN0-Hook[in0-hook] evaluiert zu: $(shell (echo "Hallo Welt - will it break?") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [""] ||  echo  [failure])" && \
        pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
-    echo "Lilly IN1-Hook[in1-hook] evaluiert zu: $(shell (echo "Hallo Welt"&&echo "Wuff  Duffel") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [success] ||  echo  ["It])" && \
+    echo "Lilly IN1-Hook[in1-hook] evaluiert zu: $(shell (echo "Hallo Welt"&&echo "Wuff  Duffel") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [success] ||  echo  ["It is dead"])" && \
        pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
-    echo "Lilly IN2-Hook[in2-hook] evaluiert zu: $(shell (echo "Hallo Welt 2") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [success] ||  echo  ["It])" && \
+    echo "Lilly IN2-Hook[in2-hook] evaluiert zu: $(shell (echo "Hallo Welt 2") >$(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && echo  [success] ||  echo  ["It's dead"])" && \
        pdflatex -jobname $(basename ${1}$${bm}-${2}) $(LATEXARGS) \\providecommand{\\LILLYxBOXxMODE}{$${bm}}\\providecommand{\\LILLYxPDFNAME}{${1}$${bm}-${2}}  ${3} $(_LILLYARGS) ${4}>> $(OUTPUTDIR)LILLY_COMPILE.log 2>&1 && \
        echo "\033[38;2;102;250;0mGenerierierung von "${1}$${bm}-${2}" ($${bm}) abgeschlossen\033[m"; done &&\
     echo "Lilly POST-Hook[hello-world-out] evaluiert zu: $(shell echo Hello World - I am out)" && \
